# Generated by Django 4.0 on 2021-12-28 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deputado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField(unique=True)),
                ('nome', models.CharField(max_length=300)),
                ('nome_civil', models.CharField(max_length=300)),
                ('sigla_uf', models.CharField(max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('situacao', models.CharField(max_length=300)),
                ('condicao_eleitoral', models.CharField(max_length=300)),
                ('cpf', models.CharField(max_length=11)),
                ('sexo', models.CharField(max_length=1)),
                ('website', models.URLField(blank=True, null=True)),
                ('data_nascimento', models.DateField()),
                ('data_falecimento', models.DateField(blank=True, null=True)),
                ('uf_nascimento', models.CharField(max_length=2)),
                ('municipio_nascimento', models.CharField(max_length=300)),
                ('escolaridade', models.CharField(max_length=300)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.IntegerField()),
                ('sigla', models.CharField(max_length=300, unique=True)),
                ('nome', models.CharField(max_length=300)),
                ('lider', models.CharField(max_length=300)),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.TextField()),
                ('cod_documento', models.IntegerField(unique=True)),
                ('data_documento', models.DateField()),
                ('num_documento', models.CharField(max_length=300)),
                ('url_documento', models.URLField()),
                ('nome_fornecedor', models.CharField(max_length=300)),
                ('valor_liquido', models.FloatField()),
                ('deputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.deputado')),
            ],
        ),
        migrations.AddField(
            model_name='deputado',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.partido'),
        ),
    ]
