# Generated by Django 4.0 on 2021-12-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partido',
            name='lider',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
