# Generated by Django 4.0 on 2022-01-03 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_deputado_escolaridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputado',
            name='partido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='backend.partido'),
        ),
    ]
