# Generated by Django 4.0 on 2022-01-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_deputado_partido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deputado',
            name='foto',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='partido',
            name='logo',
            field=models.URLField(),
        ),
    ]
